# Generated by Django 5.2.7 on 2025-10-09 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='RecoverySaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Default', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sale_no', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_status', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'wet'), (2, 'dry'), (3, 'leaves')], default=1)),
                ('create_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('delete_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_by_sale', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saler_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
