# Generated by Django 5.2.7 on 2025-10-09 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_purchase_name_recoverysaleproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverysaleproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saler_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
