# Generated by Django 5.2.7 on 2025-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_recoverysaleproduct_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverypurchase',
            name='purchase_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recoverysaleproduct',
            name='sale_no',
            field=models.CharField(max_length=255),
        ),
    ]
