# Generated by Django 5.2.7 on 2025-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_userprofile_employee_type_worklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_type',
            field=models.IntegerField(choices=[(1, 'Fixed Daily Worker'), (2, 'Casual Worker')], default=1),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='time_out',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
