# Generated by Django 5.2.7 on 2025-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_userprofile_employee_type_alter_worklog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
