# Generated by Django 5.2.7 on 2025-10-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_worklog_time_in_alter_worklog_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='paystatus',
            field=models.BooleanField(default=False),
        ),
    ]
