# Generated by Django 5.2.7 on 2025-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_worklog_paystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='time_out',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
