# Generated by Django 5.2.7 on 2025-10-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_worklog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='performance_amount',
        ),
    ]
