# Generated by Django 5.2.7 on 2025-10-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.AddField(
            model_name='salary',
            name='worklog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='project.worklog'),
            preserve_default=False,
        ),
    ]
