# Generated by Django 5.2.7 on 2025-10-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_salary_worklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='worklog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='project.worklog'),
        ),
    ]
